name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Upload to NIployments register
      uses: NIAEFEUP/push-to-niployments@v2
      with:
        NIPLOYMENTS_REGISTRY_URL: ${{ vars.NIPLOYMENTS_REGISTRY_URL }}
        NIPLOYMENTS_REGISTRY_USERNAME: ${{ vars.NIPLOYMENTS_REGISTRY_USERNAME }}
        NIPLOYMENTS_REGISTRY_PASSWORD: ${{ secrets.NIPLOYMENTS_REGISTRY_PASSWORD }}
        docker_dockerfile: Dockerfile